questions = (
    "Who sang 'Billie Jean'?",
    "Which band released the album 'Rumours'?",
    "Which song features the lyrics 'Here I am, rock you like a hurricane'?",
    "Who sang 'Time After Time'?",
    "Who sang 'Sweet Dreams (Are Made of This)'?",
    "Which band released the album 'Back in Black'?",
    "What year did the song 'Eye of the Tiger' come out?",
    "Who sang 'Girls Just Want to Have Fun'?",
    "Which song starts with the lyrics 'Just a small-town girl'?",
    "Who sang 'Like a Virgin'?",
    "What was the name of the band that sang 'Every Breath You Take'?",
    "Which artist sang 'Purple Rain'?",
    "What is the name of the band who sang 'Sweet Child O' Mine'?",
    "Who sang 'Livin' on a Prayer'?",
    "Which artist sang 'Faith'?",
    "Which artist released the song 'Thriller'?",
    "Who sang 'Take On Me'?",
    "Which artist sang 'I Wanna Dance with Somebody'?",
    "Who released the song 'Under Pressure' with Queen?",
    "What year did the song 'Livin' on a Prayer' come out?",
)